"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ArmCartesianCmd(object):
    __slots__ = ["utime", "tcp_pose", "gripper_pos", "preview_time"]

    def __init__(self):
        self.utime = 0
        self.tcp_pose = [ 0.0 for dim0 in range(6) ]
        self.gripper_pos = 0.0
        self.preview_time = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(ArmCartesianCmd._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>6d', *self.tcp_pose[:6]))
        buf.write(struct.pack(">dd", self.gripper_pos, self.preview_time))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ArmCartesianCmd._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ArmCartesianCmd._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ArmCartesianCmd()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.tcp_pose = struct.unpack('>6d', buf.read(48))
        self.gripper_pos, self.preview_time = struct.unpack(">dd", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ArmCartesianCmd in parents: return 0
        tmphash = (0x1fcddd6927a57eb8) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ArmCartesianCmd._packed_fingerprint is None:
            ArmCartesianCmd._packed_fingerprint = struct.pack(">Q", ArmCartesianCmd._get_hash_recursive([]))
        return ArmCartesianCmd._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

