"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class ArmJointCmd(object):

    __slots__ = ["utime", "num_joints", "joint_pos", "gripper_pos", "preview_time"]

    __typenames__ = ["int64_t", "int32_t", "double", "double", "double"]

    __dimensions__ = [None, None, ["num_joints"], None, None]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.num_joints = 0
        """ LCM Type: int32_t """
        self.joint_pos = []
        """ LCM Type: double[num_joints] """
        self.gripper_pos = 0.0
        """ LCM Type: double """
        self.preview_time = 0.0
        """ LCM Type: double """

    def encode(self):
        buf = BytesIO()
        buf.write(ArmJointCmd._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.num_joints))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.joint_pos[:self.num_joints]))
        buf.write(struct.pack(">dd", self.gripper_pos, self.preview_time))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ArmJointCmd._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ArmJointCmd._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ArmJointCmd()
        self.utime, self.num_joints = struct.unpack(">qi", buf.read(12))
        self.joint_pos = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        self.gripper_pos, self.preview_time = struct.unpack(">dd", buf.read(16))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ArmJointCmd in parents: return 0
        tmphash = (0x7e16406a31aaaeb2) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ArmJointCmd._packed_fingerprint is None:
            ArmJointCmd._packed_fingerprint = struct.pack(">Q", ArmJointCmd._get_hash_recursive([]))
        return ArmJointCmd._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ArmJointCmd._get_packed_fingerprint())[0]

