"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ArmState(object):
    __slots__ = ["utime", "num_joints", "joint_pos", "tcp_pose", "gripper_pos"]

    def __init__(self):
        self.utime = 0
        self.num_joints = 0
        self.joint_pos = []
        self.tcp_pose = [ 0.0 for dim0 in range(6) ]
        self.gripper_pos = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(ArmState._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.num_joints))
        buf.write(struct.pack('>%dd' % self.num_joints, *self.joint_pos[:self.num_joints]))
        buf.write(struct.pack('>6d', *self.tcp_pose[:6]))
        buf.write(struct.pack(">d", self.gripper_pos))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ArmState._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ArmState._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ArmState()
        self.utime, self.num_joints = struct.unpack(">qi", buf.read(12))
        self.joint_pos = struct.unpack('>%dd' % self.num_joints, buf.read(self.num_joints * 8))
        self.tcp_pose = struct.unpack('>6d', buf.read(48))
        self.gripper_pos = struct.unpack(">d", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ArmState in parents: return 0
        tmphash = (0x8c02205c491c613a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ArmState._packed_fingerprint is None:
            ArmState._packed_fingerprint = struct.pack(">Q", ArmState._get_hash_recursive([]))
        return ArmState._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

