"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class ArmServiceCmd(object):

    __slots__ = ["utime", "command"]

    __typenames__ = ["int64_t", "int32_t"]

    __dimensions__ = [None, None]

    HOME = 1
    PASSIVE = 2

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.command = 0
        """ LCM Type: int32_t """

    def encode(self):
        buf = BytesIO()
        buf.write(ArmServiceCmd._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.command))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ArmServiceCmd._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ArmServiceCmd._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = ArmServiceCmd()
        self.utime, self.command = struct.unpack(">qi", buf.read(12))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if ArmServiceCmd in parents: return 0
        tmphash = (0xea36cac516d8f564) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if ArmServiceCmd._packed_fingerprint is None:
            ArmServiceCmd._packed_fingerprint = struct.pack(">Q", ArmServiceCmd._get_hash_recursive([]))
        return ArmServiceCmd._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", ArmServiceCmd._get_packed_fingerprint())[0]

